name: Release

on:
  push:
    branches:
      - main
      - test

    tags:
      - '*'

env:
      PLATFORMS: "['amd64', 'arm64', 'armv7', 'armv6']"

jobs:
  docker-build:
    runs-on: ubuntu-22.04

#    outputs:
#      platforms: ${{ steps.extract-binaries.outputs.PLTF }}

    steps:
      - name: Extract binaries
        id: extract-binaries
        shell: bash
        run: |
          PLATFORMS=$(echo "${{ env.PLATFORMS }}" | sed 's/[]'"[]//g')
          echo "PLTF=($PLATFORMS)"
      #    echo "PLTF=${{ env.PLATFORMS }}" | tee -a "${GITHUB_OUTPUT}"

  upload-binaries:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    needs: docker-build
    strategy:
      matrix:
        platforms: ${{ fromJSON(env.PLATFORMS) }}

    steps:
      - name: Test
        run: |
          echo "${{ matrix.platforms }}"
